spring:
  application:
    name: My AI Chat
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 10000
      max-lifetime: 1800000
      pool-name: MyAiChatHikariPool
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 1MB # Maximum size for a single file
      max-request-size: 2MB # Maximum size for the entire request
aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
