spring:
  application:
    name: My AI Chat
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 10000
      max-lifetime: 1800000
      pool-name: MyAiChatHikariPool
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB # Maximum size for a single file
      max-request-size: 2MB # Maximum size for the entire request
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:placeholder-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:placeholder-client-secret}
            scope: user:email,read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
server:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
cdn: ${CDN_DOMAIN}
aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET_NAME}
files:
  max-mb-size: 1 # This is MB
app:
  base-url: ${APP_BASE_URL}
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  oauth2:
    success-redirect-url: ${OAUTH2_SUCCESS_REDIRECT_URL}
