name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/personalwebapss:myaichatapi-springboot

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.2.1
        env:
          DOCKERHUB_USER: ${{ vars.DOCKERHUB_USERNAME }}
          CDN_DOMAIN: ${{ vars.CDN_DOMAIN }}
          ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_PROJECT_ID: ${{ secrets.GEMINI_PROJECT_ID }}
          GEMINI_LOCATION: ${{ secrets.GEMINI_LOCATION }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
          HOST_VAIG_US_KEY_PATH: ${{ secrets.HOST_VAIG_US_KEY_PATH }}
          DB_URL: ${{ secrets.DB_URL }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          OAUTH2_SUCCESS_REDIRECT_URL: ${{ vars.OAUTH2_SUCCESS_REDIRECT_URL }}
          APP_BASE_URL: ${{ vars.APP_BASE_URL }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          envs: DOCKERHUB_USER,CDN_DOMAIN,ALLOWED_ORIGINS,DOCKERHUB_TOKEN,OPENAI_API_KEY,GEMINI_PROJECT_ID,GEMINI_LOCATION,GOOGLE_APPLICATION_CREDENTIALS,HOST_VAIG_US_KEY_PATH,DB_URL,S3_ACCESS_KEY,S3_SECRET_KEY,S3_BUCKET_NAME, GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET,JWT_SECRET,JWT_EXPIRATION,OAUTH2_SUCCESS_REDIRECT_URL,APP_BASE_URL
          script_path: scripts/deploy.sh
